### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by k2pajero** [k2pajero/furima_28756#13]
#URL
https://furima-28756.herokuapp.com/

#BASIC認証　
ID: admini　PW: 1425

#出品者情報（太郎）
e-Mail: ttt@gmail.com  PW: 1qazxsw2

#購入者情報（花子）
e-mail: hhh@gmail.com  PW: 1qazxsw2

#PAYJP test card 情報
Num: 4242424242424242  m/y: 03/24  cvc: 123

※WASの画像保存機能のみ追加実装済みです

**Comment by mutorisa** [comment]
大山さん、ご提出ありがとうございます！
挙動確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
追加実装もされており、素晴らしいですね！！
おめでとうございます✨

**※確認したのは必須機能のみで追加実装した機能については確認していません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるかご自身で再度確認をお願いいたします。**
